all: clean build run
build:
	gcc ./src/ex_1.c -o ./bin/ex_1.out -Wall
	gcc ./src/ex_3.c -o ./bin/ex_3.out -Wall
	gcc ./src/ex_4.c -o ./bin/ex_4.out -Wall
	gcc ./src/ex_7.c -o ./bin/ex_7.out -Wall
	gcc ./src/ex_8.c -o ./bin/ex_8.out -Wall
	gcc ./src/ex_10.c -o ./bin/ex_10.out -Wall
	gcc ./src/ex_13.c -o ./bin/ex_13.out -Wall
run:
	./bin/./ex_1.out
	./bin/./ex_3.out
	./bin/./ex_4.out
	./bin/./ex_7.out
	./bin/./ex_8.out
	./bin/./ex_10.out
	./bin/./ex_13.out
clean:
	rm ./bin/*.out
