all: clean build run
build:
	gcc ./src/ex_1.c -o ./bin/ex_1.out
	gcc ./src/ex_2.c -o ./bin/ex_2.out
	gcc ./src/ex_3.c -o ./bin/ex_3.out
	gcc ./src/ex_4.c -o ./bin/ex_4.out
	gcc ./src/ex_5.c -o ./bin/ex_5.out
	gcc ./src/ex_6.c -o ./bin/ex_6.out
run:
	./bin/./ex_1.out
	./bin/./ex_2.out
	./bin/./ex_3.out
	./bin/./ex_4.out
	./bin/./ex_5.out
	./bin/./ex_6.out
clean:
	rm ./bin/*.out
