all: clean build run
clean:
	rm ./bin/*.out
build:
	gcc ./src/client2.c -o ./bin/client.out -Wall
run:
	echo "TO run the program enter below command\n./client.out <server_ip> <file_name>"
##	./bin/client.out
