all: clean build run
build:
	gcc ./src/ex_3.c -o ./bin/ex_3.out -Wall -lm
	gcc ./src/ex_5.c -o ./bin/ex_5.out -Wall -lm
run:
	./bin/./ex_3.out
	./bin/./ex_5.out
clean:
	rm ./bin/ex_3.out
	rm ./bin/ex_5.out
