all: clean build run 
build:
	gcc ./src/ex_4.c -o ./bin/ex_4.out
	gcc ./src/ex_5.c -o ./bin/ex_5.out
	gcc ./src/ex_6.c -o ./bin/ex_6.out
run:
	./bin/./ex_4.out
	./bin/./ex_5.out
	./bin/./ex_6.out
clean:
	rm ./bin/*.out
