all: clean build run
build:
	gcc ./src/ex_1.c -o ./bin/ex_1.out
	gcc ./src/ex_6.c -o ./bin/ex_6.out
	gcc ./src/ex_11.c -o ./bin/ex_11.out
run:
	./bin/./ex_1.out
	./bin/./ex_6.out
	./bin/./ex_11.out
clean:
	rm ./bin/*.out
